Implementation of major refucktoring as we discussed on Siberalem :lying_face: :trollface:
ahmet/dibek pull request #1
Opened 2021-04-08 09:20 UTC by hdogan

- [x] Rename project
- [x] Refucktor code base

2021-04-08 10:58 UTC, ahmet commented
I think instead of removing one of them it'd be better we combine both and let anyone to choose her/his flavor, wdyt? :)

2021-04-08 11:20 UTC, umutphp requested changes

2021-04-08 11:20 UTC, umutphp commented on main.php
> +echo json_encode($response);
A contribution, small for me but big for code quality :)

> All PHP files MUST end with a single blank line. 
> [PHP FIG](https://www.php-fig.org/psr/psr-12/#22-files)

2021-04-08 11:36 UTC, hdogan commented on main.php
> +echo json_encode($response);
Fock PHP FIG and their nonsense *MUST* recommendations. But I'll make that change 😸

2021-04-08 11:52 UTC, hdogan commented
> I think instead of removing one of them it'd be better we combine both and let anyone to choose her/his flavor, wdyt? :)

Shall they live together in same branch/repository?

I hate golang<sup>1</sup>, golang fan boys stop mentioning "gopher" word, it's a protocol <sup>[2]</sup>, it doesn't belong to golang 😡 

<sup>1</sup> Hating golang might be supposed to be a sarcasm. :trollface: 
<sup>2</sup> https://tools.ietf.org/html/rfc1436

2021-04-09 11:27 UTC, ahmet commented
> Shall they live together in same branch/repository?

Doesn't matter as I'm the only one using this repo. The alternative may be you creating a dibek-php repo and we backlink each other in the readme 🤓

> golang fan boys stop mentioning "gopher" word, it's a protocol [2], it doesn't belong to golang 😡

Man, you're reminding me that I'm old 🥲

2023-05-20 23:01 UTC, merged